### ISSUE TITLE
toyexample1.Rmd does not knit

### ISSUE THREAD

**Issue by gustavdelius** [juliablanchard/HowToMizer#1]
When trying to knit toyexample1.Rmd I get an "Error in log(dat): non-numeric argument to mathematical function".

Perhaps, to make it easier to view the documents even without having to knit them each time, also commit the html output to GitHub.

**Comment by baldrech** [comment]
toyexample1.Rmd knits now and the corresponding html has been uploaded. The Rshiny app is not evaluated in the html at the moment.
